### ISSUE TITLE
Incorrect generated md5 value when input string contains the '+' character.

### ISSUE THREAD

**Issue by MiguelVis** [blueimp/JavaScript-MD5#29]
The library generates incorrect md5 value when the input string contains the '+' character.

ie - input string `"md+5"`.

This library generates `b3e9d0c4bfb740663e04afe467ada0c3`.

Right value is `a2a6e4f7245a3aa0c0845133073f00bc`.

**Comment by TL-Luca-Ricci** [comment]
> Right value is `a2a6e4f7245a3aa0c0845133073f00bc`.

Not really.

As you can check from any proper online md5 sites or from your unix shell
`echo -n "md+5" | md5sum`
> This library generates `b3e9d0c4bfb740663e04afe467ada0c3`.

The one that is generated by the library is the correct one.

**Comment by blueimp** [comment]
@MiguelVis
You're likely using `application/x-www-form-urlencoded` data (e.g. URL query parameters), where `md+5` is decoded to `md 5` (plus to space character).

You can see that `md 5` is the original input for your md5 hash (`a2a6e4f7245a3aa0c0845133073f00bc`) here:
http://hashtoolkit.com/decrypt-md5-hash/a2a6e4f7245a3aa0c0845133073f00bc
(as a side note, don't use md5 for any security sensitive operations, as it's often very easy to retrieve the original input)
