### ISSUE TITLE
substitution of unescape 

### ISSUE THREAD

**Issue by Leooonard** [blueimp/JavaScript-MD5#30]
`unescape` is not recommended to use now，so is there any substitution?

> The unescape() function computes a new string in which hexadecimal escape sequences are replaced with the character that it represents. The escape sequences might be introduced by a function like escape. **Usually, decodeURI or decodeURIComponent are preferred over unescape.**

**Comment by blueimp** [comment]
`unescape(encodeURIComponent(input))` is used to encode a string from JavaScript's native [UCS-2](https://en.wikipedia.org/wiki/Universal_Coded_Character_Set) character set to [UTF-8](https://en.wikipedia.org/wiki/UTF-8).

Here's an explanation on why this works:
http://monsur.hossa.in/2012/07/20/utf-8-in-javascript.html

I'm not aware of an alternative solution that has such broad browser support, plus this is done in two method calls, so helps with keeping a small file size.
