### ISSUE TITLE
这个js加密后。服务端该怎么解密呢？

### ISSUE THREAD

**Issue by memoryoverflow** [blueimp/JavaScript-MD5#37]

**Comment by zhangchenglin** [comment]
如果是密码，一般服务器也不直接存储明文密码，而是存储加密后的内容和当时加密的方式，然后进行对比。

**Comment by blueimp** [comment]
Hi @memoryoverflow,

I've translated your question using [Google Translate](https://translate.google.com/?sl=auto&tl=en&text=%E8%BF%99%E4%B8%AAjs%E5%8A%A0%E5%AF%86%E5%90%8E%E3%80%82%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%AF%86%E5%91%A2%EF%BC%9F) as unfortunately, I don't speak chinese:
> After this js is encrypted. How should the server decrypt it?

[MD5](https://en.wikipedia.org/wiki/MD5) is a [Cryptographic hash function](https://en.wikipedia.org/wiki/Cryptographic_hash_function) and not an encryption algorithm.

A typical use case is to hash input data for later comparison against the same hash value.
e.g. the [Gravatar](https://gravatar.com/) service stores profile pictures and [maps the MD5 sum of an email address to a stored profile picture](https://en.gravatar.com/site/implement/hash/). This way, you can reference profile pictures of your users without having to expose their email addresses.

Please note that MD5 should not be used to generate hashes for sensitive data, as it's [cryptographically broken](https://en.wikipedia.org/wiki/MD5#Security).

**Comment by memoryoverflow** [comment]
明白了 这个是不可逆的，也只能通过明文进行md5 后比对。是这样子的吗

**Comment by blueimp** [comment]
@zhangchenglin 

I've [translated](https://translate.google.com/?sl=auto&tl=en&text=%E5%A6%82%E6%9E%9C%E6%98%AF%E5%AF%86%E7%A0%81%EF%BC%8C%E4%B8%80%E8%88%AC%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B9%9F%E4%B8%8D%E7%9B%B4%E6%8E%A5%E5%AD%98%E5%82%A8%E6%98%8E%E6%96%87%E5%AF%86%E7%A0%81%EF%BC%8C%E8%80%8C%E6%98%AF%E5%AD%98%E5%82%A8%E5%8A%A0%E5%AF%86%E5%90%8E%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C%E5%BD%93%E6%97%B6%E5%8A%A0%E5%AF%86%E7%9A%84%E6%96%B9%E5%BC%8F%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E5%AF%B9%E6%AF%94%E3%80%82) your comment as well:

> If it is a password, the general server does not directly store the plaintext password, but stores the encrypted content and the encryption method at that time, and then compares it.

Please do not use MD5 to store password hashes, as it is [inherently insecure](https://en.wikipedia.org/wiki/MD5#Security).
Instead, use a [password hashing function](https://en.wikipedia.org/wiki/Cryptographic_hash_function#Password_verification) designed for this use case, such as [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2), [scrypt](https://en.wikipedia.org/wiki/Scrypt) or [Argon2](https://en.wikipedia.org/wiki/Argon2).

**Comment by zhangchenglin** [comment]
> 明白了 这个是不可逆的，也只能通过明文进行md5 后比对。是这样子的吗

在这整个GitHub网站中，请使用英语进行交流提问，能得到作者和维护者的更合适的解答。
In this entire GitHub website, please use English to communicate and ask questions to get more appropriate answers from the author and maintainer.

**Comment by blueimp** [comment]
Closing this as solved.
