### ISSUE TITLE
Support for es modules usage?

### ISSUE THREAD

**Issue by quantuminformation** [blueimp/JavaScript-MD5#38]
I tried ` import Md5 from "blueimp-md5"`
but get
Uncaught SyntaxError: The requested module '/@modules/blueimp-md5/js/md5.js' does not provide an export named 'default'

 I tried
 ```js


import * as Md5 from "blueimp-md5"

 Md5(email)

```
but get Uncaught TypeError: Cannot set property 'md5' of undefined

**Comment by blueimp** [comment]
Hi @quantuminformation,

are you using [ES modules through NodeJS](https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs) or a transpiler like Babel or TypeScript?

I've used ES module imports successfully with the following minimal steps, using NodeJS version 15:

```sh
mkdir example
echo 'import md5 from "blueimp-md5";
console.log(md5(...process.argv.slice(2)));' > example/index.js
echo '{"type": "module"}' > example/package.json
npm install --prefix example blueimp-md5
node example value
```

Can you confirm if this works for you?

**Comment by AleksandrSl** [comment]
I used `import md5 from "blueimp-md5"` in our web app, all works fine

**Comment by blueimp** [comment]
Closing as solved.
